[build]
  command = """
  pip install -r requirements.txt;
  cd docs;
  BASE_URL=compass myst build --html --execute;
  mkdir -p publish/docs
  cp -r _build/html/* publish/docs/
  """
  publish = "publish/"